import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

// eslint-config-next 16 ships flat configs directly, so no FlatCompat shim.
const eslintConfig = [
  ...coreWebVitals,
  ...typescript,
  {
    // Generated by `prisma generate`; not ours to lint.
    ignores: ["src/generated/**", ".next/**", "node_modules/**", "scripts/**"],
  },
];

export default eslintConfig;
